### ISSUE TITLE
plugin is incompatible with QGIS version

### ISSUE THREAD

**Issue by sharish33** [locusrobotics/qgis_ros#11]
Hi,

I found this page useful in my project  and I tried to use the plugin.I have successfully installed the QGIS and plugin. But when i open the plugin to enable qgis_ros , it is showing the below error.

"This plugin is incompatible with this version of QGIS
Plugin designed for QGIS 3.0 - 3.99"

I also tried to do some work arounds to resolve the issue but not successful. Any suggested resolution will be great and helpful.

Best Regards,
Hareesh

![error](https://user-images.githubusercontent.com/51229156/70126134-a9dde680-1678-11ea-8cc2-357ed679ff14.png)

**Comment by ablakey** [comment]
Sorry to hear that.

What versions are you running of:

- QGIS
- Your OS
- Python 3 ?

**Comment by sharish33** [comment]
Hi Ablakey,

Thank you for your reply. I installed the QGIS 2.18 previously which shows the version incompatible error. Now I removed the QGIS 2.18 totally and trying to install QGIS 3.x , but resulting in errors. This question may be not belong here but if you have faced such issues please could you suggest some solution.

![image](https://user-images.githubusercontent.com/51229156/70181422-248f1c00-16e2-11ea-8684-deddde7ecefd.png)

What versions are you running of:

> * QGIS - (Trying to install 3.x)
> * Your OS -(Ubuntu 16.04)
> * Python 3  - ( python 3.5)

Best Regards,
Hareesh

**Comment by ablakey** [comment]
Yeah unfortunately I cannot help you too much with that.  What I can say is that I did have trouble reconciling the right version of everything I needed to make QGIS  + ROS + Python 3 all behave properly together in Ubuntu 16.04. I had a lot more success in Ubuntu 18.04.   You might consider trying this on a machine or VM running 18.04.

**Comment by sharish33** [comment]
Thank you.

I finally installed QGIS 3.x in 16.04 and qgis_ros Plugin is enabled now.For may be someone who is struggling with the same issue, below is the useful link for installation using Package Manager Aptitude -

https://stackoverflow.com/a/42048214

Best Regards,
Hareesh
